### ISSUE TITLE
Ability to annotate and label a namespace

### ISSUE THREAD

**Issue by distorhead** [werf/werf#1936] opened 2019-11-25 12:25 UTC
- Auto werf annotations: `project.werf.io/env`, `project.werf.io/name`, `project.werf.io/env`.
 - Annotations added by `--add-annotation` flag.
 - Labels added by `--add-label` flag.

Open question: how to deal with namespaces hardcoded in the templates?

**Comment by viperx77** [comment] 2021-02-18 03:19
Is there any way to accomplish this yet? I need my namespace labeled for istio-injection

**Comment by viperx77** [comment] 2021-03-26 16:29
No progress?

**Comment by ilya-lesikov** [comment] 2024-06-14 11:37
Currently if you need to add some labels/annotations to the release namespace the easiest way is to `kubectl label/annotate myns ...` after `werf converge`.

Alternatively, you can do `kubectl create ns myns` yourself, then `kubectl label/annotate`, then `werf converge`.

Duplicate of #4195.

**Closed by ilya-lesikov** 2024-06-14 11:37 UTC
Labels: type: feature, scope: deploy, priority: normal
