### ISSUE TITLE
Do not create namespace automatically

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2238] opened 2020-03-11 09:39 UTC
When deploying non-namespaces resources it is unnecessary to create namespace resource and specify namespace (`--env`).

Namespace should be automatically created if there are at least one namespaced resource defined in the templates.

`--annotate` and `--label` options should work with namespace resource as well.

There should be a way to define namespace resource in the helm templates.

Related to https://github.com/flant/werf/issues/2237.

**Comment by ilya-lesikov** [comment] 2024-06-14 10:55
> When deploying non-namespaces resources it is unnecessary to create namespace resource and specify namespace (--env).
> Namespace should be automatically created if there are at least one namespaced resource defined in the templates.
We can't do that. We _must_ create a namespace if we are going to deploy a release. Secret/ConfigMap with release data is a namespaced resource, thus requires release namespace to be present. The only exception is MySQL release storage backend, but barely anyone uses it.

**Comment by ilya-lesikov** [comment] 2024-06-14 10:56
The rest is the duplicate of #4195

**Closed by ilya-lesikov** 2024-06-14 10:56 UTC
Labels: type: feature, scope: deploy, priority: normal
