### ISSUE TITLE
build stapel without docker

### ISSUE THREAD

**Issue by sasokol** [werf/werf#4422] opened 2022-05-05 17:44 UTC
Run in container without docker host
ENV:
  WERF_BUILDAH_FOR_STAPEL_ENABLED: 1
  WERF_BUILDAH_MODE: auto
$ werf converge
`...
Error: unable to create docker cli: unable to resolve docker endpoint: open /docker-certs/client/ca.pem: no such file or directory`

$ werf version
v1.2.95

**Comment by distorhead** [comment] 2022-05-05 21:30
Did you use official image with builtin werf as suggested in the docs https://werf.io/documentation/v1.2/advanced/ci_cd/run_in_container/use_gitlab_ci_cd_with_kubernetes_executor.html?

**Comment by sasokol** [comment] 2022-05-06 07:17
No, I used self-build image with gitlab-runner executor docker.

**Comment by ilya-lesikov** [comment] 2022-05-06 08:10
Can you try to use one of the official images, e. g. `registry.werf.io/werf/werf:1.2`? Full list of available images here: https://werf.io/documentation/v1.2/advanced/ci_cd/run_in_container/how_it_works.html#available-werf-images

If you want to customize the image you can use one of our images as a base image and build your own on top of ours.

**Comment by alexey-igrychev** [comment] 2024-06-03 21:05
Hi, @sasokol!

We haven't encountered similar issues, and we couldn't reproduce the problem. To help us investigate further, please provide more context about the issue, including the image you're using and any specific configurations. This additional information will be valuable for diagnosing and resolving the problem.

**Closed** 2024-07-31 15:00 UTC
Labels: type: bug, scope: build, solved, 👀 awaiting response, scope: buildah
