### ISSUE TITLE
docs: "User-defined regular values" is incorrect — `global` doesn't work

### ISSUE THREAD

**Issue by develar** [werf/werf#3639] opened 2021-08-02 07:28 UTC
Version: v1.2.12+fix2

[Docs](https://werf.io/documentation/v1.2.13/advanced/helm/configuration/values.html#user-defined-regular-values) stated that 

> Values placed under the global key will be available both in the current chart and in all subcharts.

but actually it doesn't work, 

```
global:
  ingress:
    host: localhost
```

leads to 

> Error: helm templates rendering failed: template: app/templates/003-ingress.yaml:9:22: executing "app/templates/003-ingress.yaml" at <.Values.ingress.host>: nil pointer evaluating interface {}.host

```
ingress:
  host: localhost
```

works.

What is the proper way to define user values?

The second issue is that for non-nested properties, it doesn't report unresolved variables, and `null` is inserted instead.

Also, docs is confusing regarding dev/staging/production separation — example contains `staging` / `production`, but not confirmed that it will work or how does it work. For example, DevSpace provides profiles for that — https://devspace.sh/cli/docs/configuration/profiles/patches

**Comment by develar** [comment] 2021-08-02 14:34
> example contains staging / production, but not confirmed that it will work or how does it work

Solved, I found https://werf.io/documentation/v1.2/advanced/helm/configuration/templates.html#environment

**Comment by evgkrsk** [comment] 2022-04-22 13:12
Актуально на сегодня с werf-1.2.90 (через werf helm template и werf template в helm-режиме воспроизводится).

**Comment by ilya-lesikov** [comment] 2022-04-22 18:12
Answer to the original problem: global Values should be referenced as `$.Values.global.ingress.host`, not `$.Values.ingress.host`.

To the last commentator: this was a different problem, `$.Values.global.env` was overridden by werf, which is by design at the moment. We'll look into what we can do with this.

Closing this issue. You are free to open a new one if you wish.

**Closed by ilya-lesikov** 2022-04-22 18:12 UTC
