### ISSUE TITLE
Remote execution without submodule

### ISSUE THREAD

**Issue by onegreyonewhite** [werf/werf#4948] opened 2022-09-19 00:46 UTC
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

Some projects require to separate codebase and infra settings in different git repositories. The main solution is using git submodules or bundles.
But:
* Submodule requires manual update infra repo. This is difficult/impossible in web-ide. There is no mechanism for semver autoupdate.
* Bundles requires making copy in each infra repo. You can't build containers with infra files.

This solutions always requires manual actions from infrastructure's administration. That's not DevOps way.

### Solution (if you have one)

There are two ways which I see:
* werf remote sublevel of command (werf remote converge/build/etc).
* Provide functionality to setup/import werf.yaml in remote repo with connection settings. Like in `.gitlab-ci.yaml`

### Additional information

It would be great to support connect on tags with semver or branch with auto fetch.

**Comment by alexey-igrychev** [comment] 2022-09-19 16:56
rel https://github.com/werf/werf/issues/4873

**Comment by ilya-lesikov** [comment] 2024-05-31 17:46
> Provide functionality to setup/import werf.yaml in remote repo with connection settings. Like in .gitlab-ci.yaml
This will be the solution, so I will close this as a duplicate of #4873

**Closed by ilya-lesikov** 2024-05-31 17:46 UTC
Labels: priority: normal
