### ISSUE TITLE
deploy upgrade silently fails

### ISSUE THREAD

**Issue by gkappel** [werf/werf#2799] opened 2020-10-20 18:51 UTC
werf v1.1.22+fix31

werf deploy works the first time but when image is updated and werf deploy is run again it says it succeeds and a new deploy revision record is created but the associated pods are not updated or replaced

see following log excerpt, nothing useful is logged "Waiting for release resources" happens instantly which should not happen
...
3.507161523s ┌ Running pre-deploy
3.507194923s │ ┌ Checking release
3.512890232s │ ├ Info
3.512915732s │ │ revision: 2
3.512927632s │ │ revision-status: DEPLOYED
3.512937733s │ └ Checking release (0.01 seconds)
3.512951533s └ Running pre-deploy (0.01 seconds)
3.512985834s 
3.512986734s Getting chart templates ... (0.00 seconds)
3.517415118s Running helm upgrade...
3.517737924s Using three-way-merge mode "enabled"
4.713833985s 
4.713851286s ┌ Waiting for release resources to become ready
4.732302837s │ ┌ Status progress
4.732739445s │ │ DEPLOYMENT                                                            REPLICAS     AVAILABLE     UP-TO-DATE               
4.732800646s │ │ test-prod                                                                2/2          2             2                        
4.73296695s  │ └ Status progress
4.73300435s  └ Waiting for release resources to become ready (0.02 seconds)

...

**Comment by gkappel** [comment] 2020-10-20 21:17
this can be worked around by adding a timestamp annotation to helm templates

**Comment by distorhead** [comment] 2020-11-05 14:51
Hello! To use werf.yaml images correctly in v1.1 you need to specify `werf_container_image` and `werf_container_env` templates.

werf_container_env will generate environments variable section, which would contain DOCKER_IMAGE_ID environment variable in the case of using tag-or-branch tagging scheme. This variable will change when a new docker image has been built.

https://werf.io/v1.1-stable/documentation/reference/deploy_process/deploy_into_kubernetes.html#integration-with-built-images

**Comment by gkappel** [comment] 2020-11-17 01:02
Thanks for the info, currently things are configured with custom tagging not tag-or-branch.  Seems it is recommended to not use custom tagging?

**Comment by distorhead** [comment] 2020-11-17 13:28
@gkappel Seems that documentation is a little bit outdated, because for custom tagging strategy `werf_container_env` template also generates `DOCKER_IMAGE_ID` env variable which will cause restart of Pods with changed images:

https://github.com/werf/werf/blob/release-v1.1.23/pkg/deploy/helm/templates.go#L440

### About tagging strategies

It is ok to use custom tagging strategy when you really need it. But for now the only recommended tagging strategy is content-based. Furthermore in the v1.2 version it will be the only "strategy" available (there will also be ability to force custom tags, but without automatic DOCKER_IMAGE_ID generation).

Content based tagging strategy gives user reproducible and stable docker images tags, which depend on the history of the git repo and depend on the content of built images. It is not a simple commit-id tags, because content-based tag will change only when corresponding image has been changed. It also gives an isolation of tags between different branches that do not fully share git history.

The benefits of werf content-based tags over tag-or-branch strategy:
 - If an application contains multiple images: A, B and C and there is an update to the new version v1.0.0 -> v1.0.1. In the case of tag-or-branch strategy there will be pushed 3 new images A:v1.0.1, B:v1.0.1 and C:v1.0.1. Then during deploy process each deployment (or some other resource kind) should restart all pods to use new version. In the case of content-based tagging only changed images will be pushed with new tags and then only corresponding Pods will restart.
 - Tagging by branch name may result in a situation when pipeline of some old commit of the branch rewrites published image by branch name, which may result in unpredictable consequences, which is hard to debug.

Werf also has an ability to inject arbitrary annotations and labels to deployed resources. It is supposed that such info of the application as semver version will be added to the deployed resources this way.

**Comment by ilya-lesikov** [comment] 2024-05-29 17:16
No issue, closing.

**Closed by ilya-lesikov** 2024-05-29 17:16 UTC
